## Notebook of code highlighting data tranformations of csv file provided by Wei

Importing pandas and numpy libraries to modify data. This notebook is in the same downloads folder as State_Level_Suicide_Data.csv file so there is no need to specify full path when reading in file

In [1]:
import pandas as pd
import numpy as np

# Set ipython's max row display
pd.set_option('display.max_row', 1000)

# Set iPython's max column width to 50
pd.set_option('display.max_columns', 50)

Reading in file to take a look at data

In [2]:
df = pd.read_csv("State_Level_Suicide_Data.csv")

df.head(5)

sitecode  year  survyear   weight                      age  sex grade  \
0  Alabama  1991         1  98.1638                      NaN  NaN   NaN   
1  Alabama  1991         1  69.1663  12 years old or younger  NaN  10th   
2  Alabama  1991         1  80.3232             13 years old  NaN  11th   
3  Alabama  1991         1  66.5061             15 years old  NaN  10th   
4  Alabama  1991         1  89.3992             16 years old  NaN   9th   

             race4  race7      q26      q27      q28      q29  qn26  qn27  \
0              NaN    NaN  Missing  Missing  Missing  Missing   NaN   NaN   
1  All other races    NaN  Missing  Missing  Missing  Missing   NaN   NaN   
2            White  White  Missing  Missing  Missing  Missing   NaN   NaN   
3            White  White  Missing  Missing  Missing  Missing   NaN   NaN   
4            White  White  Missing  Missing  Missing  Missing   NaN   NaN   

   qn28  qn29  
0   NaN   NaN  
1   NaN   NaN  
2   NaN   NaN  
3   NaN   NaN  
4   NaN   NaN

Number of rows and columns in file

In [3]:
df.shape

(1536948, 17)

Since Wei used SAS to look at data and export as csv file, it looks like the width of the text columns are maxed at the first row. So there are high odds that some of the text within our observations are truncated. So, given Tom's preference to use data UNI provided, we need to take a look at data and correct errors when necessary.

Let's first take a look at the `sitecode` column

In [4]:
df.sitecode.unique()

array(['Alabama', 'Georgia', 'Idaho', 'Hawaii', 'Illinoi', 'Mississ',
       'Montana', 'Alaska', 'Arkansa', 'Maine', 'Missour', 'Connect',
       'Iowa', 'Kentuck', 'Louisia', 'Michiga', 'Delawar', 'Florida',
       'Arizona', 'Colorad', 'Kansas', 'Marylan', 'Califor', 'Nebrask',
       'New Mex', 'South C', 'South D', 'Utah', 'North C', 'New Ham',
       'Nevada', 'Tenness', 'Vermont', 'Wiscons', 'West Vi', 'North D',
       'Wyoming', 'New Yor', 'Rhode I', 'New Jer', 'Texas', 'Oklahom',
       'Pennsyl', 'Virgini'], dtype=object)

There are definite errors in `sitecode` that needs to be fixed before importing into Tableau

In [5]:
df.loc[df.sitecode == 'Mississ', 'sitecode'] = 'Mississippi'
df.loc[df.sitecode == 'Illinoi', 'sitecode'] = 'Illinois'
df.loc[df.sitecode == 'Arkansa', 'sitecode'] = 'Arkansas'
df.loc[df.sitecode == 'Missour', 'sitecode'] = 'Missouri'
df.loc[df.sitecode == 'Connect', 'sitecode'] = 'Connecticut'
df.loc[df.sitecode == 'Kentuck', 'sitecode'] = 'Kentucky'
df.loc[df.sitecode == 'Louisia', 'sitecode'] = 'Louisiana'
df.loc[df.sitecode == 'Michiga', 'sitecode'] = 'Michigan'
df.loc[df.sitecode == 'Delawar', 'sitecode'] = 'Delaware'
df.loc[df.sitecode == 'Colorad', 'sitecode'] = 'Colorado'
df.loc[df.sitecode == 'Marylan', 'sitecode'] = 'Maryland'
df.loc[df.sitecode == 'Califor', 'sitecode'] = 'California'
df.loc[df.sitecode == 'Nebrask', 'sitecode'] = 'Nebraska'
df.loc[df.sitecode == 'New Mex', 'sitecode'] = 'New Mexico'
df.loc[df.sitecode == 'South C', 'sitecode'] = 'South Carolina'
df.loc[df.sitecode == 'South D', 'sitecode'] = 'South Dakota'
df.loc[df.sitecode == 'North C', 'sitecode'] = 'North Carolina'
df.loc[df.sitecode == 'New Ham', 'sitecode'] = 'New Hampshire'
df.loc[df.sitecode == 'Tenness', 'sitecode'] = 'Tennessee'
df.loc[df.sitecode == 'Wiscons', 'sitecode'] = 'Wisconsin'
df.loc[df.sitecode == 'West Vi', 'sitecode'] = 'West Virginia'
df.loc[df.sitecode == 'North D', 'sitecode'] = 'North Dakota'
df.loc[df.sitecode == 'New Yor', 'sitecode'] = 'New York'
df.loc[df.sitecode == 'Rhode I', 'sitecode'] = 'Rhode Island'
df.loc[df.sitecode == 'New Jer', 'sitecode'] = 'New Jersey'
df.loc[df.sitecode == 'Oklahom', 'sitecode'] = 'Oklahoma'
df.loc[df.sitecode == 'Pennsyl', 'sitecode'] = 'Pennsylvania'
df.loc[df.sitecode == 'Virgini', 'sitecode'] = 'Virginia'

Let's make sure `sitecode` is fixed

In [6]:
df.sitecode.unique()

array(['Alabama', 'Georgia', 'Idaho', 'Hawaii', 'Illinois', 'Mississippi',
       'Montana', 'Alaska', 'Arkansas', 'Maine', 'Missouri',
       'Connecticut', 'Iowa', 'Kentucky', 'Louisiana', 'Michigan',
       'Delaware', 'Florida', 'Arizona', 'Colorado', 'Kansas', 'Maryland',
       'California', 'Nebraska', 'New Mexico', 'South Carolina',
       'South Dakota', 'Utah', 'North Carolina', 'New Hampshire',
       'Nevada', 'Tennessee', 'Vermont', 'Wisconsin', 'West Virginia',
       'North Dakota', 'Wyoming', 'New York', 'Rhode Island',
       'New Jersey', 'Texas', 'Oklahoma', 'Pennsylvania', 'Virginia'],
      dtype=object)

Now let's look at our `age` column

In [7]:
df.age.unique()

array([nan, '12 years old or younger', '13 years old', '15 years old',
       '16 years old', '14 years old', '17 years old',
       '18 years old or older'], dtype=object)

Let's look at the `sex` column

In [8]:
df.sex.unique()

array([nan, 'Male', 'Fema'], dtype=object)

'Female' got clipped, so let's fix that

In [9]:
df.loc[df.sex == 'Fema', 'sex'] = 'Female'

In [10]:
df.sex.unique()

array([nan, 'Male', 'Female'], dtype=object)

Checking out `grade` column

In [11]:
df.grade.unique()

array([nan, '10th', '11th', '9th', '12th'], dtype=object)

Let's now look at `race4`

In [12]:
df.race4.unique()

array([nan, 'All other races', 'White', 'Black or African American',
       'Hispanic/Latino'], dtype=object)

Checking out `race7`

In [13]:
df.race7.unique()

array([nan, 'White', 'Black or African American', 'Asian',
       'Am Indian / Alaska Native', 'Hispanic/Latino',
       'Native Hawaiian/other PI', 'Multiple - Non-Hispanic'],
      dtype=object)

Now we're looking at the responses of the suicidal questions.

The data dictionary for these responses are located [here on page 22](https://www.cdc.gov/healthyyouth/data/yrbs/pdf/2017/2017_YRBS_Data_Users_Guide.pdf)

`q26`: During the past 12 months, did you ever seriously consider attempting suicide? <br>
`q27`: During the past 12 months, did you make a plan about how you would attempt suicide?<br> 
`q28`: During the past 12 months, how many times did you actually attempt suicide? <br>
`q29`: If you attempted suicide during the past 12 months, did any attempt result in an injury, poisoning, or overdose that
had to be treated by a doctor or nurse?<br>
<br>
The columns starting with 'qn' are supposed to by numerator/denominator rates, but I cannot see how that can be used. So I think it's best to change the "yes/no" responses to "1/0" and create a denominator column, so that rates can be generated

In [14]:
# q26,q27,q28,q29,qn26,qn27,qn28,qn29
print(df.q26.unique())
print(df.q27.unique())
print(df.q28.unique())
print(df.q29.unique())
print(df.qn26.unique())
print(df.qn27.unique())
print(df.qn28.unique())
print(df.qn29.unique())

['Missing' 'No' 'Yes']
['Missing' 'No' 'Yes']
['Missing' '0 times' '6 or mo' '2 or 3' '1 time' '4 or 5']
['Missing' 'Did not' 'Yes' 'No']
[nan  2.  1.]
[nan  2.  1.]
[nan  2.  1.]
[nan  2.  1.]


Adjusting and creating columns for `q26` and `q27`

In [15]:
conditions = [(df['q26']=='Yes'),(df['q26']=='No'),(df['q26']=='Missing')]
values = [1,0,np.nan]
df['q26_num']  = np.select(conditions, values)

df['q26_num'] = df['q26_num'] * df['weight'] 

conditions = [(df['q26']=='Yes')|(df['q26']=='No'),(df['q26']=='Missing')]
values = [1,0]
df['q26_denom']  = np.select(conditions, values)

df['q26_denom'] = df['q26_denom'] * df['weight'] 

conditions = [(df['q27']=='Yes'),(df['q27']=='No'),(df['q27']=='Missing')]
values = [1,0,np.nan]
df['q27_num']  = np.select(conditions, values)

df['q27_num'] = df['q27_num'] * df['weight'] 

conditions = [(df['q27']=='Yes')|(df['q27']=='No'),(df['q27']=='Missing')]
values = [1,0]
df['q27_denom']  = np.select(conditions, values)

df['q27_denom'] = df['q27_denom'] * df['weight'] 

df[['q26','q26_num','q26_denom','q27','q27_num','q27_denom']][df['q26_denom']>=1].head(10)

q26   q26_num  q26_denom  q27   q27_num  q27_denom
2477   No    0.0000   116.4746   No    0.0000   116.4746
2478  Yes  157.9206   157.9206  Yes  157.9206   157.9206
2480   No    0.0000   157.5833   No    0.0000   157.5833
2481  Yes  134.9657   134.9657   No    0.0000   134.9657
2485   No    0.0000   140.5893   No    0.0000   140.5893
2486  Yes  108.2884   108.2884  Yes  108.2884   108.2884
2487  Yes  199.8180   199.8180  Yes  199.8180   199.8180
2488   No    0.0000   108.2884   No    0.0000   108.2884
2489  Yes  108.2884   108.2884  Yes  108.2884   108.2884
2490   No    0.0000   135.3606   No    0.0000   135.3606

Fixing `q28`

In [16]:
df.loc[df.q28 == '2 or 3', 'q28'] = '2 or 3 times'
df.loc[df.q28 == '4 or 5', 'q28'] = '4 or 5 times'
df.loc[df.q28 == '6 or mo', 'q28'] = '6 or more times'

Fixing and creating columns for `q29`

In [17]:
df.loc[df.q29 == 'Did not', 'q29'] = 'I did not attempt suicide during the past 12 months'

conditions = [(df['q29']=='Yes'),
              (df['q29']=='No'),
              (df['q29']=='Missing'),
              (df['q29']=='I did not attempt suicide during the past 12 months')]
values = [1,0,np.nan,np.nan]
df['q29_num']  = np.select(conditions, values)

df['q29_num'] = df['q29_num'] * df['weight'] 

conditions = [(df['q29']=='Yes')|(df['q29']=='No'),
              (df['q29']=='Missing'),
              (df['q26']=='I did not attempt suicide during the past 12 months')]
values = [1,np.nan,0]
df['q29_denom']  = np.select(conditions, values)

df['q29_denom'] = df['q29_denom'] * df['weight']

df[['q29','q29_num','q29_denom']][df['q29_denom']>=1].head()

q29   q29_num  q29_denom
2484  Yes  127.3982   127.3982
2499   No    0.0000   145.3873
2509   No    0.0000   108.2884
2606   No    0.0000   127.8380
2615  Yes  137.2737   137.2737

#### These next few steps are an attempt to flag non-participating states and survey waves where states did not participate by assigning a "-1" in survey weight. This will allow us to do maps in a single layer where we can flag (e.g., assign Black color" to states that did not particpate in a particular wave

First we are going to index all the survey years using the following columns `year` and `surveyyear`

In [18]:
states = df.groupby(['sitecode']).size().reset_index(name='counts')
survey_Yrs = df.groupby(['year','survyear']).size().reset_index(name='counts')
survey_Yrs.head()

year  survyear  counts
0  1991         1   26323
1  1993         2   55995
2  1995         3   48943
3  1997         4   56120
4  1999         5   41796

Now we are going to import the fifty states using a table in [Wiki](https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States).<br> Since some of the states have a [E] or [F] next to them, we will have to do some "find and replacing."

In [19]:
WIKI_URL = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"
dfs = pd.read_html(WIKI_URL, header=0) # set header with row #0
state_list=dfs[0]
state_list=state_list.drop([0, 0])
state_list=state_list[['Flag, name andpostal abbreviation[12]']]
state_list.columns = ['sitecode']
state_list['sitecode'] = state_list['sitecode'].str.replace('\[E\]', '')
state_list['sitecode'] = state_list['sitecode'].str.replace('\[F\]', '')
state_list.head()

sitecode
1     Alabama
2      Alaska
3     Arizona
4    Arkansas
5  California

Now we are going to do a cross-join for all survey years and states as the primary table to do a left join on

In [20]:
key_Table = state_list.assign(foo=1).merge(survey_Yrs[['year','survyear']].assign(foo=1)).drop('foo', 1)
key_Table.shape

(750, 3)

Now we are doing a  one-to-many left join to keep all possible `State` and `year` combinations with our survey data. States that did not participate and survey years where other styates did not participate will have a "null" response in `survyear`

In [21]:
new_df = pd.merge(key_Table[['sitecode','year']], df,  how='left', on=['sitecode','year'])
new_df.head()

sitecode  year  survyear   weight                      age  sex grade  \
0  Alabama  1991       1.0  98.1638                      NaN  NaN   NaN   
1  Alabama  1991       1.0  69.1663  12 years old or younger  NaN  10th   
2  Alabama  1991       1.0  80.3232             13 years old  NaN  11th   
3  Alabama  1991       1.0  66.5061             15 years old  NaN  10th   
4  Alabama  1991       1.0  89.3992             16 years old  NaN   9th   

             race4  race7      q26      q27      q28      q29  qn26  qn27  \
0              NaN    NaN  Missing  Missing  Missing  Missing   NaN   NaN   
1  All other races    NaN  Missing  Missing  Missing  Missing   NaN   NaN   
2            White  White  Missing  Missing  Missing  Missing   NaN   NaN   
3            White  White  Missing  Missing  Missing  Missing   NaN   NaN   
4            White  White  Missing  Missing  Missing  Missing   NaN   NaN   

   qn28  qn29  q26_num  q26_denom  q27_num  q27_denom  q29_num  q29_denom  
0   NaN   NaN      NaN        0.0      NaN        0.0      NaN        NaN  
1   NaN   NaN      NaN        0.0      NaN        0.0      NaN        NaN  
2   NaN   NaN      NaN        0.0      NaN        0.0      NaN        NaN  
3   NaN   NaN      NaN        0.0      NaN        0.0      NaN        NaN  
4   NaN   NaN      NaN        0.0      NaN        0.0      NaN        NaN

In [22]:
new_df[new_df['weight'].isnull()].head()

sitecode  year  survyear  weight  age  sex grade race4 race7  q26  q27  \
20488  Alabama  2007       NaN     NaN  NaN  NaN   NaN   NaN   NaN  NaN  NaN   
26506  Alabama  2017       NaN     NaN  NaN  NaN   NaN   NaN   NaN  NaN  NaN   
28547   Alaska  1991       NaN     NaN  NaN  NaN   NaN   NaN   NaN  NaN  NaN   
28548   Alaska  1993       NaN     NaN  NaN  NaN   NaN   NaN   NaN  NaN  NaN   
30183   Alaska  1997       NaN     NaN  NaN  NaN   NaN   NaN   NaN  NaN  NaN   

       q28  q29  qn26  qn27  qn28  qn29  q26_num  q26_denom  q27_num  \
20488  NaN  NaN   NaN   NaN   NaN   NaN      NaN        NaN      NaN   
26506  NaN  NaN   NaN   NaN   NaN   NaN      NaN        NaN      NaN   
28547  NaN  NaN   NaN   NaN   NaN   NaN      NaN        NaN      NaN   
28548  NaN  NaN   NaN   NaN   NaN   NaN      NaN        NaN      NaN   
30183  NaN  NaN   NaN   NaN   NaN   NaN      NaN        NaN      NaN   

       q27_denom  q29_num  q29_denom  
20488        NaN      NaN        NaN  
26506        NaN      NaN        NaN  
28547        NaN      NaN        NaN  
28548        NaN      NaN        NaN  
30183        NaN      NaN        NaN

Let's make sure there is a null response in `survyear`

In [23]:
new_df.survyear.unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., nan, 10., 11., 12., 13.,
       15.,  9., 14.])

In an experiment, I realized that ~1 million rows is too much, so since weights are accounted for in our responses, we are going to aggregate the rows to compress size of file so that it is responsive. I'm gonna drop the 'qn' columns because I cannot figure out value in their presence

In [24]:
list(new_df.columns) 

['sitecode',
 'year',
 'survyear',
 'weight',
 'age',
 'sex',
 'grade',
 'race4',
 'race7',
 'q26',
 'q27',
 'q28',
 'q29',
 'qn26',
 'qn27',
 'qn28',
 'qn29',
 'q26_num',
 'q26_denom',
 'q27_num',
 'q27_denom',
 'q29_num',
 'q29_denom']

Now we are going to assign a "-1" in waves where a state did not participate, and remove the null values in `survyear`. Also, will use the `year` column to create a date for Tableau because line charts are a little easier with dates on X-axis.

In [25]:
new_df.loc[new_df['weight'].isnull(), 'weight'] = -1
new_df.loc[new_df.year == 1991, 'survyear'] = 1
new_df.loc[new_df.year == 1993, 'survyear'] = 2
new_df.loc[new_df.year == 1995, 'survyear'] = 3
new_df.loc[new_df.year == 1997, 'survyear'] = 4
new_df.loc[new_df.year == 1999, 'survyear'] = 5
new_df.loc[new_df.year == 2001, 'survyear'] = 6
new_df.loc[new_df.year == 2003, 'survyear'] = 7
new_df.loc[new_df.year == 2005, 'survyear'] = 8
new_df.loc[new_df.year == 2007, 'survyear'] = 9
new_df.loc[new_df.year == 2009, 'survyear'] = 10
new_df.loc[new_df.year == 2011, 'survyear'] = 11
new_df.loc[new_df.year == 2013, 'survyear'] = 12
new_df.loc[new_df.year == 2015, 'survyear'] = 13
new_df.loc[new_df.year == 2017, 'survyear'] = 14
new_df.loc[new_df.year == 2019, 'survyear'] = 15

Aggregating values

In [26]:
new_df['year_date'] = '01-01-'+new_df['year'].map(str)
new_df=new_df[['sitecode','year','year_date',
                'survyear', 'weight',
                'age', 'sex', 'grade', 'race4', 
                'race7', 'q26', 'q27', 'q28', 
                'q29', 'q26_num', 'q26_denom', 
                'q27_num', 'q27_denom', 'q29_num', 
                'q29_denom']].groupby(by=['sitecode','year','year_date',
                                       'survyear','age', 'sex', 'grade', 'race4',
                                       'race7', 'q26', 'q27', 'q28','q29'], 
                                      dropna=False).sum()
new_df.reset_index(level=['sitecode','year', 'year_date','survyear',
                          'age','sex','grade','race4','race7',
                          'q26','q27','q28','q29'], inplace=True)
new_df.head()

sitecode  year   year_date  survyear                      age     sex grade  \
0  Alabama  1991  01-01-1991       1.0  12 years old or younger  Female  10th   
1  Alabama  1991  01-01-1991       1.0  12 years old or younger  Female  11th   
2  Alabama  1991  01-01-1991       1.0  12 years old or younger    Male  11th   
3  Alabama  1991  01-01-1991       1.0  12 years old or younger     NaN  10th   
4  Alabama  1991  01-01-1991       1.0             13 years old    Male  10th   

                       race4                      race7      q26      q27  \
0            Hispanic/Latino            Hispanic/Latino  Missing  Missing   
1            All other races                      Asian  Missing  Missing   
2  Black or African American  Black or African American  Missing  Missing   
3            All other races                        NaN  Missing  Missing   
4  Black or African American  Black or African American  Missing  Missing   

       q28      q29   weight  q26_num  q26_denom  q27_num  q27_denom  q29_num  \
0  Missing  Missing  63.5111      0.0        0.0      0.0        0.0      0.0   
1  Missing  Missing  69.6732      0.0        0.0      0.0        0.0      0.0   
2  Missing  Missing  73.9484      0.0        0.0      0.0        0.0      0.0   
3  Missing  Missing  69.1663      0.0        0.0      0.0        0.0      0.0   
4  Missing  Missing  78.2424      0.0        0.0      0.0        0.0      0.0   

   q29_denom  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0

Just checking to see if non-participating states are included in data

In [27]:
new_df[new_df['sitecode']=='Washington'].head()

sitecode  year   year_date  survyear  age  sex grade race4 race7  \
247033  Washington  1991  01-01-1991       1.0  NaN  NaN   NaN   NaN   NaN   
247034  Washington  1993  01-01-1993       2.0  NaN  NaN   NaN   NaN   NaN   
247035  Washington  1995  01-01-1995       3.0  NaN  NaN   NaN   NaN   NaN   
247036  Washington  1997  01-01-1997       4.0  NaN  NaN   NaN   NaN   NaN   
247037  Washington  1999  01-01-1999       5.0  NaN  NaN   NaN   NaN   NaN   

        q26  q27  q28  q29  weight  q26_num  q26_denom  q27_num  q27_denom  \
247033  NaN  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0   
247034  NaN  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0   
247035  NaN  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0   
247036  NaN  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0   
247037  NaN  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0   

        q29_num  q29_denom  
247033      0.0        0.0  
247034      0.0        0.0  
247035      0.0        0.0  
247036      0.0        0.0  
247037      0.0        0.0

In [28]:
new_df[new_df['weight']<0].head()

sitecode  year   year_date  survyear  age  sex grade race4 race7  q26  \
3244  Alabama  2007  01-01-2007       9.0  NaN  NaN   NaN   NaN   NaN  NaN   
4996  Alabama  2017  01-01-2017      14.0  NaN  NaN   NaN   NaN   NaN  NaN   
5577   Alaska  1991  01-01-1991       1.0  NaN  NaN   NaN   NaN   NaN  NaN   
5578   Alaska  1993  01-01-1993       2.0  NaN  NaN   NaN   NaN   NaN  NaN   
6008   Alaska  1997  01-01-1997       4.0  NaN  NaN   NaN   NaN   NaN  NaN   

      q27  q28  q29  weight  q26_num  q26_denom  q27_num  q27_denom  q29_num  \
3244  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0      0.0   
4996  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0      0.0   
5577  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0      0.0   
5578  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0      0.0   
6008  NaN  NaN  NaN    -1.0      0.0        0.0      0.0        0.0      0.0   

      q29_denom  
3244        0.0  
4996        0.0  
5577        0.0  
5578        0.0  
6008        0.0

Now exporting clean csv file

In [29]:
new_df.to_csv("State_Level_Suicide_Data_cleaned_2020OCT28.csv", index=False)